version: '3.7'
services:
  web:
    image: ldiiso/react-app:1.0.0
    ports:
      - target: 80
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=80

